# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- feature/sitepublic

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Step to run tests (optional)
- script: npm test
  displayName: 'Run tests'

# Step to analyze code (optional)
- task: ESLint@1
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    eslintArguments: '--ext .js,.jsx'
    failOnError: true
  displayName: 'Run ESLint'

# Step to archive build artifacts
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/.next'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/sitioPublico .zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifacts'

# Step to publish artifacts
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/sitioPublico .zip'
    artifact: 'sitioPublico '
    publishLocation: 'pipeline'
  displayName: 'Publish build artifacts'

# Step to deploy to Azure App Service (example, adjust as necessary)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Your Azure Subscription'
    appName: 'Your App Name'
    package: '$(Build.ArtifactStagingDirectory)/sitioPublico .zip'
    startupCommand: 'npm start'  # or your specific command to start the app
  displayName: 'Deploy to Azure Web App'
